### ISSUE TITLE
领域模型没有设置主键时，会导致IShardingBootstrapper启动时报空引用错误

### ISSUE THREAD

**Issue by jjyangbiu** [dotnetcore/sharding-core#128]
### 情形
构造了一个没有主键的领域模型
> 在`OnModelCreating`内使用`entity.HasNoKey()`进行声明领域模型无主键
### 报错日志
```
 Application startup exception
   System.NullReferenceException: Object reference not set to an instance of an object.
   at ShardingCore.Bootstrapers.EntityMetadataInitializer`2.Initialize()
   at ShardingCore.Bootstrapers.ShardingDbContextBootstrapper`1.InitializeEntityMetadata()
   at ShardingCore.Bootstrapers.ShardingDbContextBootstrapper`1.Init()
   at ShardingCore.Bootstrapers.ShardingBootstrapper.Start()
```

**Comment by xuejmnet** [comment]
@jjyangbiu  升级到x.4.2.1+版本,已修复
