### ISSUE TITLE
wtm + sharding-core migration

### ISSUE THREAD

**Issue by iioter** [dotnetcore/sharding-core#164]
我是WTM重度用户，通过你的Demo可以在WTM中正常使用分表，但是无法进行CodeFirst迁移，需要指导一下:
`add-migration ini`
报错:
`
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ShardingCore.Exceptions.ShardingCoreInvalidOperationException: sharding core not start
   at ShardingCore.ShardingContainer.get_ServiceProvider()
   at ShardingCore.ShardingContainer.GetRequiredVirtualDataSourceManager(Type shardingDbContextType)
   at ShardingCore.ShardingContainer.GetRequiredVirtualDataSourceManager[TShardingDbContext]()
   at ShardingCore.ShardingContainer.GetRequiredCurrentVirtualDataSource[TShardingDbContext]()
   at ShardingCore.Sharding.ShardingDbContextExecutors.ShardingDbContextExecutor`1..ctor(DbContext shardingDbContext)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at LKDispatcher.DataAccess.AbstractShardingFrameworkContext..ctor(String cs, DBTypeEnum dbtype) in D:\000000-LKZN\LKDispatcher2.0\src\LKDispatcher.DataAccess\AbstractShardingFrameworkContext.cs:line 41
   at LKDispatcher.DataAccess.DataContext..ctor(String cs, DBTypeEnum dbtype) in D:\000000-LKZN\LKDispatcher2.0\src\LKDispatcher.DataAccess\DataContext.cs:line 24
   at LKDispatcher.DataAccess.DataContextFactory.CreateDbContext(String[] args) in D:\000000-LKZN\LKDispatcher2.0\src\LKDispatcher.DataAccess\DataContext.cs:line 82
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory, Type contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass21_2.<FindContextTypes>b__9()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
`

**Comment by xuejmnet** [comment]
@iioter 您好,很高兴您关注我的框架 错误目前来看是 sharding core not start,可以很明确,这边简单说下，efcore.tool提供了迁移的能力就是你输入的add-migration init但是efcore.tool有个地方有点问题,就是如果他发现当前项目下有startup的依赖注入会优先使用startup的依赖注入,但是不会执行`public void Configure(IApplicationBuilder app, IWebHostEnvironment env)`,那么就会导致ShardingCore没有办法启动,又因为ShardingCore需要先初始化也就是start一下,所以这边会有个冲突,如果你需要code-first，这边建议你在创建一个新的控制台项目,然后使用DesignTimeDbContextFactory类来进行code-first，那么就可以支持了 [code-first](https://xuejm.gitee.io/sharding-core-doc/adv/code-first/) ,具体可以参考文档或者我的文章[abp的codefirst](https://www.cnblogs.com/xuejiaming/p/15449819.html) 如果还不行可以加群这边会给你解决谢谢

**Comment by xuejmnet** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18061232/175504398-0c511cc3-6a04-4ecc-bf39-d9cd0f551372.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/18061232/175504482-be9ebcbf-48be-4b15-b341-aadb669e81be.png">

**Comment by xuejmnet** [comment]
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/18061232/175506535-a6272c23-6c45-4122-9f43-862d6eaf8aca.png">

**Comment by xuejmnet** [comment]
代码提交了不知道你说的是哪种
