### ISSUE TITLE
非索引字段 OrderBy 不支持string 和int32 以外的字段类型

### ISSUE THREAD

**Issue by zh3305** [dotnetcore/sharding-core#216]
非int ,String 类型字段排序出错

```Csharp

     public virtual ulong Mileage { get; set; }


property:[Mileage] not in type:[<>f__AnonymousType47`2[System.Nullable`1[System.Int32],System.String]]
ShardingCore.Exceptions.ShardingCoreException: property:[Mileage] not in type:[<>f__AnonymousType47`2[System.Nullable`1[System.Int32],System.String]]
   at ShardingCore.Extensions.ExpressionExtension.GetValueByExpression(Object obj, String propertyExpression)
   at ShardingCore.Sharding.Enumerators.OrderStreamMergeAsyncEnumerator`1.GetCurrentOrderValues()
   at ShardingCore.Sharding.Enumerators.OrderStreamMergeAsyncEnumerator`1.SetOrderValues()
   at ShardingCore.Sharding.Enumerators.StreamMergeAsync.MultiOrderStreamMergeAsyncEnumerator`1.SetOrderEnumerator()
   at ShardingCore.Sharding.Enumerators.StreamMergeAsync.MultiOrderStreamMergeAsyncEnumerator`1..ctor(StreamMergeContext mergeContext, IEnumerable`1 enumerators)
   at ShardingCore.Sharding.Enumerators.StreamMergeAsync.PaginationStreamMergeAsyncEnumerator`1..ctor(StreamMergeContext mergeContext, IEnumerable`1 sources, Nullable`1 skip, Nullable`1 take)
   at ShardingCore.Sharding.MergeEngines.Executors.ShardingMergers.AbstractEnumerableShardingMerger`1.StreamInMemoryMerge(List`1 parallelResults)
   at ShardingCore.Sharding.MergeEngines.Executors.ShardingMergers.AbstractEnumerableShardingMerger`1.InMemoryMerge(List`1 beforeInMemoryResults, List`1 parallelResults)
   at ShardingCore.Sharding.MergeEngines.Executors.Abstractions.AbstractExecutor`1.ExecuteAsync0(Boolean async, DataSourceSqlExecutorUnit dataSourceSqlExecutorUnit, CancellationToken cancellationToken)
   at ShardingCore.Sharding.MergeEngines.Executors.Abstractions.AbstractExecutor`1.ExecuteAsync(Boolean async, DataSourceSqlExecutorUnit dataSourceSqlExecutorUnit, CancellationToken cancellationToken)
   at ShardingCore.Sharding.MergeEngines.ShardingExecutors.ShardingExecutor.<>c__DisplayClass7_1`1.<<Execute0>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at ShardingCore.Sharding.MergeEngines.ShardingExecutors.ShardingExecutor.ExecuteAsync[TResult](StreamMergeContext streamMergeContext, IExecutor`1 executor, Boolean async, IEnumerable`1 sqlRouteUnits, CancellationToken cancellationToken)
   at ShardingCore.Extensions.TaskExtension.WaitAndUnwrapException[TResult](Task`1 task)
   at ShardingCore.Sharding.MergeEngines.ShardingExecutors.ShardingExecutor.Execute[TResult](StreamMergeContext streamMergeContext, IExecutor`1 executor, Boolean async, IEnumerable`1 sqlRouteUnits, CancellationToken cancellationToken)
   at ShardingCore.Sharding.MergeEngines.ShardingMergeEngines.Abstractions.StreamMerge.AbstractStreamEnumerable`1.GetStreamMergeAsyncEnumerator(Boolean async, CancellationToken cancellationToken)
   at ShardingCore.Sharding.MergeEngines.ShardingMergeEngines.Abstractions.StreamMerge.AbstractStreamEnumerable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at ShardingCore.Sharding.MergeEngines.EnumeratorStreamMergeEngines.AsyncEnumeratorStreamMergeEngine`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToDictionaryAsync[TSource,TKey,TElement](IQueryable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken)
  
```

**Comment by xuejmnet** [comment]
@zh3305  排序字段必须存在于select的返回结果中

**Comment by xuejmnet** [comment]
@zh3305 错误提示排序字段`Mileage`不存在于匿名对象返回结果里面,那么就无法流式聚合

**Comment by xuejmnet** [comment]
@zh3305 两个解决方案如果不是分页那么就不要再表达式上排序,可以再内存排序这样对数据库压力也轻，如果是分页的必须要排序字段那么请加到最后的select上面

**Comment by zh3305** [comment]
@xuejmnet  Select 中是包含了 Mileage 字段的, 好的🆗

> @zh3305 两个解决方案如果不是分页那么就不要再表达式上排序,可以再内存排序这样对数据库压力也轻，如果是分页的必须要排序字段那么请加到最后的select上面

**Comment by xuejmnet** [comment]
> @xuejmnet Select 中是包含了 Mileage 字段的, 好的🆗
> 
> > @zh3305 两个解决方案如果不是分页那么就不要再表达式上排序,可以再内存排序这样对数据库压力也轻，如果是分页的必须要排序字段那么请加到最后的select上面

查询结果包含了这个Mileage字段了的吗,如果包含了的话请发一下表达式可以吗我看看是什么问题

**Comment by zh3305** [comment]
抱歉,我找到原因了,是我的问题,没有select 
我是先(order by  select  )没有 Tolist()  在select  就没有包含order 字段了,
