### ISSUE TITLE
☹ShardingOracleMigrationsSqlGenerator报错

### ISSUE THREAD

**Issue by 54ble** [dotnetcore/sharding-core#239]
示例中的`ShardingOracleMigrationsSqlGenerator.cs`运行报错。
``` 
[21:24:08 ERR] 2023-04-26 21:24:08.944609 ThreadID:9   (ERROR)   OracleRelationalCommand.ExecuteNonQuery() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00955: 名称已由现有对象使用
ORA-06512: 在 line 2
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
[21:24:08 ERR] Failed executing DbCommand (115ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
```

**Comment by xuejmnet** [comment]
这个错误我查了一下貌似已经存在,你试试`Script-Migration`呢看看生成的sql是怎么样的

**Comment by xuejmnet** [comment]
@54ble 如果不行的话是否可以给个最简单的demo顺便讲一下数据库版本
