### ISSUE TITLE
任意类型的CLR类不支持查询

### ISSUE THREAD

**Issue by EmmaCCC** [dotnetcore/sharding-core#282]
![220076417cdd407e7afefbf1d3222d79](https://github.com/user-attachments/assets/346c0c34-66c2-42f5-80cb-ee7ecf8bdd9a)
这种查询 我看efcore8 是支持的，我这项目引入shardingcore报错，Cannot create a DbSet for 'SystemConfigTmp' because this type is not included in the model for the context ，去掉之后就好了，我用的
![28d4293de4faef3f894aaad1cc4526aa](https://github.com/user-attachments/assets/cb6abf83-f3d9-4029-863d-4201473937f3)
这个模型就是没在DbContext中，ef7也是不支持的，但是ef8支持任意的CLR类型
![f1e05e245955cb423f78d04b521360f6](https://github.com/user-attachments/assets/52087008-037c-44a6-a6cf-5ffb4ecd90ef)
下边是堆栈信息：
System.InvalidOperationException: Cannot create a DbSet for 'SystemConfigTmp' because this type is not included in the model for the context.
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at ShardingCore.Core.Internal.Visitors.DbContextReplaceQueryableVisitor.VisitExtension(Expression node)
   at ShardingCore.Extensions.IShardingQueryableExtension.ReplaceDbContextExpression(Expression queryExpression, DbContext dbContext)
   at ShardingCore.Sharding.ShardingExecutors.QueryCompilerExecutor..ctor(DbContext dbContext, Expression queryExpression)
   at ShardingCore.Sharding.ShardingExecutors.QueryCompilerContext.GetQueryCompilerExecutor()
   at ShardingCore.Sharding.ShardingExecutors.QueryCompilerContextFactory.Create(IPrepareParseResult prepareParseResult)
   at ShardingCore.Sharding.ShardingExecutors.DefaultShardingCompilerExecutor.ExecuteAsync[TResult](IShardingDbContext shardingDbContext, Expression query, CancellationToken cancellationToken)
   at ShardingCore.EFCores.ShardingQueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LinkDuoo.LK.Eshop.Service.SystemSecurity.SystemConfigService.GetInfo(GetSystemConfigDto dto) in D:\Projects\Work\LinkDuoo.DCC\src\LinkDuoo.DCC.Erp.Service\Basic\SystemConfigService.cs:line 40
   at LinkDuoo.DCC.Erp.ManageApi.Controllers.Basic.SystemConfigController.GetInfo(GetSystemConfigDto dto) in D:\Projects\Work\LinkDuoo.DCC\src\LinkDuoo.DCC.Erp.ManageApi\Controllers\Basic\SystemConfigController.cs:line 45
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by xuejmnet** [comment]
@EmmaCCC 已修复7.x.1.22
